apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-delete-consumer-api-deployment  # Nome do Deployment
  annotations:
    autor: Rodrigo Mahlow 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-delete-consumer-api
  template:
    metadata:
      labels:
        app: contact-delete-consumer-api
    spec:
      containers:
      - name: contact-delete-consumer-api
        image: maxcedro/contactsdeleteconsumer:latest
        ports:
        - containerPort: 5700 
        resources:
          limits:
            cpu: "0.5"
            memory: 512Mi
          requests:
            cpu: "0.2"
            memory: 256Mi
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: contact-delete-consumer-api-secrets
              key: DefaultConnection
        - name: SecretJWT
          valueFrom:
            secretKeyRef:
              name: contact-delete-consumer-api-secrets
              key: SecretJWT
        - name: MassTransit__User
          valueFrom:
            secretKeyRef:
              name: contact-delete-consumer-api-secrets
              key: User
        - name: MassTransit__Password
          valueFrom:
            secretKeyRef:
              name: contact-delete-consumer-api-secrets
              key: Password
        - name: MassTransit__QueueName
          valueFrom:
            configMapKeyRef: 
              name: "contact-delete-consumer-api-configmap"
              key: "QueueName"        
        - name: MassTransit__Server
          valueFrom:
            configMapKeyRef: 
              name: "contact-delete-consumer-api-configmap"
              key: "Server"
        
       
